[app]
host = "0.0.0.0"
port = 18081

[database]
host = "localhost"
name = "leangoodb_file_dev"
user = "root"
password = "leangoo123"
port = 13306

[oss]
access_key_id = ""
access_key_secret = ""
region = ""
end_point = ""
bucket = ""
